# Generated by Django 3.0.2 on 2020-02-19 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressDimension',
            fields=[
                ('address_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100)),
                ('balance', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'address_dimension',
            },
        ),
        migrations.CreateModel(
            name='CountryDimension',
            fields=[
                ('idcountry_dimension', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('code', models.CharField(max_length=5)),
                ('region', models.CharField(max_length=45)),
                ('currency', models.CharField(max_length=45)),
                ('currency_code', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'country_dimension',
            },
        ),
        migrations.CreateModel(
            name='DateDimension',
            fields=[
                ('date_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('day', models.BigIntegerField()),
                ('month', models.BigIntegerField()),
                ('year', models.BigIntegerField()),
            ],
            options={
                'db_table': 'date_dimension',
            },
        ),
        migrations.CreateModel(
            name='UsdExchangeRates',
            fields=[
                ('usdexchangerates_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('date_0', models.DateField(db_column='date')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ethereum_analysis_app.CountryDimension')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ethereum_analysis_app.DateDimension')),
            ],
            options={
                'db_table': 'usd_exchange_rates',
            },
        ),
        migrations.CreateModel(
            name='DaiTransactions',
            fields=[
                ('dai_transactions_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hash', models.CharField(max_length=255, unique=True)),
                ('block_number', models.DecimalField(decimal_places=1000, max_digits=1000)),
                ('value', models.FloatField()),
                ('gas', models.DecimalField(decimal_places=1000, max_digits=1000)),
                ('gas_price', models.DecimalField(decimal_places=1000, max_digits=1000)),
                ('transaction_fee', models.DecimalField(decimal_places=1000, max_digits=1000)),
                ('input', models.TextField()),
                ('block_timestamp', models.BigIntegerField()),
                ('date_0', models.DateField(db_column='date')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ethereum_analysis_app.DateDimension')),
                ('from_address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='from_address', to='ethereum_analysis_app.AddressDimension')),
                ('to_address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_address', to='ethereum_analysis_app.AddressDimension')),
            ],
            options={
                'db_table': 'dai_transactions',
            },
        ),
    ]
