# Generated by Django 3.0.2 on 2020-02-19 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ethereum_analysis_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daitransactions',
            name='from_address',
        ),
        migrations.RemoveField(
            model_name='daitransactions',
            name='to_address',
        ),
        migrations.AddField(
            model_name='daitransactions',
            name='from_address_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='from_address_id', to='ethereum_analysis_app.AddressDimension'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='daitransactions',
            name='to_address_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_address_id', to='ethereum_analysis_app.AddressDimension'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='daitransactions',
            name='block_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='daitransactions',
            name='gas',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='daitransactions',
            name='gas_price',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='daitransactions',
            name='transaction_fee',
            field=models.BigIntegerField(),
        ),
    ]
