# Generated by Django 3.0.2 on 2020-02-19 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ethereum_analysis_app', '0002_auto_20200219_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daitransactions',
            name='from_address_id',
        ),
        migrations.RemoveField(
            model_name='daitransactions',
            name='to_address_id',
        ),
        migrations.AddField(
            model_name='daitransactions',
            name='from_address',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='from_address', to='ethereum_analysis_app.AddressDimension'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='daitransactions',
            name='to_address',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_address', to='ethereum_analysis_app.AddressDimension'),
            preserve_default=False,
        ),
    ]
